import type { Plugin } from 'vite'
import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, join } from 'path'
import matter from 'gray-matter'
import { md5 } from '../utils/md5'
import { md, registerLanguages } from '../utils/highlight'
import {
  addBlankTargetToLinks,
  enhanceCodeBlocks,
} from '../utils/htmlPostProcess'

interface ArticleData {
  slug: string
  html: string
  content: string
  title: string
  date: string
  tags: string[]
  description: string
  cover?: string
  htmlFile?: string   // md5(slug) + '.html'，写文件后填充
}

async function loadArticles(rootDir: string): Promise<ArticleData[]> {
  const contentDir = resolve(rootDir, 'content')

  if (!existsSync(contentDir)) {
    console.warn('[articles-plugin] content/ directory not found')
    return []
  }

  const files = readdirSync(contentDir).filter((f) => f.endsWith('.md'))
  const articles: ArticleData[] = []

  for (const file of files) {
    try {
      const raw = readFileSync(join(contentDir, file), 'utf-8')
      const { data, content } = matter(raw)
      const slug = file.replace(/\.md$/, '')

      // 按需注册文章使用的语言，再渲染 markdown
      await registerLanguages(content)
      let html = md.render(content)
      html = addBlankTargetToLinks(html)
      html = enhanceCodeBlocks(html)

      articles.push({
        slug,
        html,
        content,
        title: data.title || slug,
        date: typeof data.date === 'object' ? String(data.date) : (data.date || ''),
        tags: data.tags || [],
        description: data.description || '',
        cover: data.cover,
      })
    } catch (e) {
      console.warn(`[articles-plugin] Failed to load: ${file}`, e)
    }
  }

  articles.sort((a, b) => (b.date || '').localeCompare(a.date || ''))
  console.log(`[articles-plugin] Loaded ${articles.length} articles`)
  return articles
}

function writeArticleHtmlFiles(rootDir: string, articles: ArticleData[]) {
  const htmlDir = resolve(rootDir, 'public', 'articles')
  if (!existsSync(htmlDir)) {
    mkdirSync(htmlDir, { recursive: true })
  }

  for (const a of articles) {
    const file = `${md5(a.slug)}.html`
    writeFileSync(join(htmlDir, file), a.html, 'utf-8')
    a.htmlFile = file
  }

  console.log(`[articles-plugin] Wrote ${articles.length} article HTML files to public/articles/`)
}

function generateSitemap(rootDir: string, articles: ArticleData[]) {
  const distDir = resolve(rootDir, 'dist')
  if (!existsSync(distDir)) {
    mkdirSync(distDir, { recursive: true })
  }

  const SITE_URL = 'https://turing158.github.io'

  const staticPages = [
    { path: '/', priority: '1.0', changefreq: 'daily' },
    { path: '/#/articles', priority: '0.9', changefreq: 'daily' },
    { path: '/#/projects', priority: '0.8', changefreq: 'weekly' },
    { path: '/#/tools', priority: '0.8', changefreq: 'weekly' },
    { path: '/#/about', priority: '0.7', changefreq: 'monthly' },
    { path: '/#/releases', priority: '0.6', changefreq: 'weekly' },
    { path: '/#/commits', priority: '0.5', changefreq: 'daily' },
  ]

  const today = new Date().toISOString().split('T')[0]

  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
`

  for (const page of staticPages) {
    xml += `  <url>
    <loc>${SITE_URL}${page.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>\n`
  }

  for (const article of articles) {
    xml += `  <url>
    <loc>${SITE_URL}/#/article/${article.slug}</loc>
    <lastmod>${article.date || today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.9</priority>
  </url>\n`
  }

  xml += '</urlset>'

  const sitemapPath = join(distDir, 'sitemap.xml')
  writeFileSync(sitemapPath, xml, 'utf-8')
  console.log(`[articles-plugin] Generated sitemap.xml (${staticPages.length + articles.length} URLs)`)
}

export function articlesPlugin(): Plugin {
  let generated = false

  return {
    name: 'vite-plugin-articles',
    enforce: 'pre',

    async configResolved(config) {
      if (generated) return
      generated = true

      const articles = await loadArticles(config.root)

      // 每篇文章生成独立的 HTML 文件，放入 public/articles/
      writeArticleHtmlFiles(config.root, articles)

      const outputPath = resolve(config.root, 'src', 'generated', '_articles-index.ts')
      const dir = resolve(config.root, 'src', 'generated')
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      // 构建轻量索引：保留 content（给搜索/阅读时间/页脚统计用），
      // 移除 html（已存入独立 HTML 文件），新增 htmlFile 引用
      const indexArticles = articles.map((a) => ({
        slug: a.slug,
        content: a.content,
        title: a.title,
        date: a.date,
        tags: a.tags,
        description: a.description,
        cover: a.cover,
        htmlFile: a.htmlFile,
      }))

      const code = `// Auto-generated by vite-plugin-articles — DO NOT EDIT\nimport type { ArticleMeta } from '../types/article'\n\nconst articles: ArticleMeta[] = ${JSON.stringify(indexArticles, null, 2)}\n\nexport default articles\n\nexport const htmlFileBySlug: Record<string, string> = Object.fromEntries(articles.map(a => [a.slug, a.htmlFile || '']))\n`
      writeFileSync(outputPath, code, 'utf-8')
      console.log(`[articles-plugin] Generated _articles-index.ts (${articles.length} articles)`)

      // 生成 sitemap.xml
      generateSitemap(config.root, articles)
    },
  }
}
