import type { Plugin } from 'vite'
import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, join } from 'path'
import matter from 'gray-matter'
import { md5 } from '../utils/md5'
import { md, registerLanguages } from '../utils/highlight'
import { articleTime } from '../utils/articleDate'
import {
  addBlankTargetToLinks,
  enhanceCodeBlocks,
} from '../utils/htmlPostProcess'
import { setBuildArticles, type BuildArticle } from './articles-store'

interface ArticleData extends BuildArticle {}

async function loadArticles(rootDir: string): Promise<ArticleData[]> {
  const contentDir = resolve(rootDir, 'content')

  if (!existsSync(contentDir)) {
    console.warn('[articles-plugin] content/ directory not found')
    return []
  }

  const files = readdirSync(contentDir).filter((f) => f.endsWith('.md'))
  const articles: ArticleData[] = []

  for (const file of files) {
    try {
      const raw = readFileSync(join(contentDir, file), 'utf-8')
      const { data, content } = matter(raw)
      const slug = file.replace(/\.md$/, '')

      // 按需注册文章使用的语言，再渲染 markdown
      await registerLanguages(content)
      let html = md.render(content)
      html = addBlankTargetToLinks(html)
      html = enhanceCodeBlocks(html)

      articles.push({
        slug,
        html,
        content,
        title: data.title || slug,
        // YAML 日期被解析为 Date 对象，序列化为 ISO 字符串，
        // 避免 String(date) 产生 "Fri Feb 09 2024 ..." 这类无法按字典序比较时间的格式
        date: data.date instanceof Date ? data.date.toISOString() : (data.date || ''),
        tags: data.tags || [],
        description: data.description || '',
        cover: data.cover,
      })
    } catch (e) {
      console.warn(`[articles-plugin] Failed to load: ${file}`, e)
    }
  }

  articles.sort((a, b) => articleTime(b.date) - articleTime(a.date))
  console.log(`[articles-plugin] Loaded ${articles.length} articles`)
  return articles
}

function writeArticleHtmlFiles(rootDir: string, articles: ArticleData[]) {
  const htmlDir = resolve(rootDir, 'public', 'articles')
  if (!existsSync(htmlDir)) {
    mkdirSync(htmlDir, { recursive: true })
  }

  for (const a of articles) {
    const file = `${md5(a.slug)}.html`
    writeFileSync(join(htmlDir, file), a.html, 'utf-8')
    a.htmlFile = file
  }

  console.log(`[articles-plugin] Wrote ${articles.length} article HTML files to public/articles/`)
}

export function articlesPlugin(): Plugin {
  let generated = false

  return {
    name: 'vite-plugin-articles',
    enforce: 'pre',

    async configResolved(config) {
      if (generated) return
      generated = true

      const articles = await loadArticles(config.root)

      // 共享给 prerender-plugin（生成文章页与 sitemap 用）
      setBuildArticles(articles)

      // 每篇文章生成独立的 HTML 文件，放入 public/articles/
      writeArticleHtmlFiles(config.root, articles)

      const outputPath = resolve(config.root, 'src', 'generated', '_articles-index.ts')
      const dir = resolve(config.root, 'src', 'generated')
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      // 构建轻量索引：保留 content（给搜索/阅读时间/页脚统计用），
      // 移除 html（已存入独立 HTML 文件），新增 htmlFile 引用
      const indexArticles = articles.map((a) => ({
        slug: a.slug,
        content: a.content,
        title: a.title,
        date: a.date,
        tags: a.tags,
        description: a.description,
        cover: a.cover,
        htmlFile: a.htmlFile,
      }))

      const code = `// Auto-generated by vite-plugin-articles — DO NOT EDIT\nimport type { ArticleMeta } from '../types/article'\n\nconst articles: ArticleMeta[] = ${JSON.stringify(indexArticles, null, 2)}\n\nexport default articles\n\nexport const htmlFileBySlug: Record<string, string> = Object.fromEntries(articles.map(a => [a.slug, a.htmlFile || '']))\n`
      writeFileSync(outputPath, code, 'utf-8')
      console.log(`[articles-plugin] Generated _articles-index.ts (${articles.length} articles)`)
    },

    // sitemap 与各页面的真实 HTML 由 prerender-plugin 在 dist 落盘后统一生成
    // （必须晚于 emptyOutDir，否则会被清掉）
  }
}
