import type { Plugin } from 'vite'
import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, join } from 'path'
import matter from 'gray-matter'
import MarkdownIt from 'markdown-it'
import anchor from 'markdown-it-anchor'
import hljs from 'highlight.js'

const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
  highlight(str: string, lang: string) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value
      } catch {
        // ignore
      }
    }
    return ''
  },
}).use(anchor, {
  // 保持标题原文作为 id，确保与文章中的手动锚点链接一致
  slugify: (s: string) => s.toString().trim(),
  permalink: false,
})

// 所有链接在新标签页打开（跳过页内锚点链接）
md.renderer.rules.link_open = function (tokens, idx, options, _env, self) {
  const token = tokens[idx]
  const href = token.attrGet('href') || ''
  // 页内锚点链接（#xxx）不添加 target="_blank"
  if (href.startsWith('#')) {
    return self.renderToken(tokens, idx, options)
  }
  const aIndex = token.attrIndex('target')
  if (aIndex < 0) {
    token.attrPush(['target', '_blank'])
  } else if (token.attrs) {
    token.attrs[aIndex][1] = '_blank'
  }
  const relIndex = token.attrIndex('rel')
  if (relIndex < 0) {
    token.attrPush(['rel', 'noopener noreferrer'])
  }
  return self.renderToken(tokens, idx, options)
}

function addBlankTargetToLinks(html: string): string {
  return html.replace(/<a\s+([^>]*)>/g, (_m: string, attrs: string) => {
    if (/target=/.test(attrs)) {
      return `<a ${attrs}>`
    }
    // 跳过锚点链接（href 以 # 开头），不添加 target="_blank"
    if (/href\s*=\s*["']#/.test(attrs)) {
      return `<a ${attrs}>`
    }
    return `<a ${attrs} target="_blank" rel="noopener noreferrer">`
  })
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
}

function enhanceCodeBlocks(html: string): string {
  return html.replace(
    /<pre><code([^>]*)>([\s\S]*?)<\/code><\/pre>/g,
    (_m: string, attrs: string, code: string) => {
      const langMatch = attrs.match(/language-(\w+)/)
      const lang = langMatch ? langMatch[1] : ''
      const decoded = decodeHtmlEntities(code)
      const b64 = Buffer.from(decoded, 'utf-8').toString('base64')
      return `<div class="code-block-wrapper">${lang ? `<span class="code-lang">${lang}</span>` : ''}<button class="code-copy-btn" data-code-b64="${b64}" title="复制代码">复制</button><pre><code${attrs}>${code}</code></pre></div>`
    }
  )
}

interface ArticleData {
  slug: string
  html: string
  content: string
  title: string
  date: string
  tags: string[]
  description: string
  cover?: string
}

function loadArticles(rootDir: string): ArticleData[] {
  const contentDir = resolve(rootDir, 'content')

  if (!existsSync(contentDir)) {
    console.warn('[articles-plugin] content/ directory not found')
    return []
  }

  const files = readdirSync(contentDir).filter((f) => f.endsWith('.md'))
  const articles: ArticleData[] = []

  for (const file of files) {
    try {
      const raw = readFileSync(join(contentDir, file), 'utf-8')
      const { data, content } = matter(raw)
      const slug = file.replace(/\.md$/, '')
      let html = md.render(content)
      html = addBlankTargetToLinks(html)
      html = enhanceCodeBlocks(html)

      articles.push({
        slug,
        html,
        content,
        title: data.title || slug,
        date: typeof data.date === 'object' ? String(data.date) : (data.date || ''),
        tags: data.tags || [],
        description: data.description || '',
        cover: data.cover,
      })
    } catch (e) {
      console.warn(`[articles-plugin] Failed to load: ${file}`, e)
    }
  }

  articles.sort((a, b) => (b.date || '').localeCompare(a.date || ''))
  console.log(`[articles-plugin] Loaded ${articles.length} articles`)
  return articles
}

export function articlesPlugin(): Plugin {
  let generated = false

  return {
    name: 'vite-plugin-articles',
    enforce: 'pre',

    configResolved(config) {
      if (generated) return
      generated = true

      const articles = loadArticles(config.root)

      const outputPath = resolve(config.root, 'src', 'generated', '_articles.ts')
      const dir = resolve(config.root, 'src', 'generated')
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      const code = `// Auto-generated by vite-plugin-articles — DO NOT EDIT\nimport type { Article } from '../types/article'\n\nconst articles: Article[] = ${JSON.stringify(articles, null, 2)}\n\nexport default articles\n`
      writeFileSync(outputPath, code, 'utf-8')
    },
  }
}
